#+TITLE: Project
#+AUTHOR: Michael Hunsinger
#+OPTIONS: \n:nil ':t f:nil
#+LaTeX_CLASS_OPTIONS: [a4paper]
#+LATEX_CLASS:  article
#+LaTeX_HEADER: \setlength\parindent{0pt}

* Setup
  The project was done using Node.js and requires Node.js along with npm to be
  installed (usually comes with Node.js). Node.js can be downloaded from the
  [[https://nodejs.org][Node.Js]] website. It can also be install through a package manager if running
  Linux.

** Build
   Once Node.js is installed, navigate to the directory containing the
   project. The node modules were not bundled and will have to be installed via
   the following command

   #+BEGIN_SRC sh
     npm install
   #+END_SRC

* Run
  After the modules are installed, you may select from the following run
  commands to execute.

** Maps
   Run the program to generate a move and reachability board for an array of pieces.

   #+BEGIN_SRC sh
     npm run maps res/input/2d-chess-pieces.json
   #+END_SRC

** Trajectories
   Run the program to generate trajectories for a given piece.

   #+BEGIN_SRC sh
     npm run trajectories res/input/2d-chess-king.json
   #+END_SRC

** Zones
   Run the program to generate trajectories for a given board.

   #+BEGIN_SRC sh
     npm run zones res/input/sample-zone.json
   #+END_SRC    
   
