#+TITLE: Assignment Four
#+AUTHOR: Michael Hunsinger
#+OPTIONS: toc:nil \n:nil ':t f:nil num:nil
#+LaTeX_CLASS_OPTIONS: [a4paper]
#+LATEX_CLASS:  article
#+LaTeX_HEADER: \setlength\parindent{0pt}
#+LaTeX_HEADER: \usepackage{titling}
#+LaTeX_HEADER: \usepackage{multicol}
#+LaTeX_HEADER: \addtolength{\topmargin}{-1.375in}
#+LaTeX_HEADER: \addtolength{\textheight}{1.75in}
#+LaTeX_HEADER: \addtolength{\oddsidemargin}{-.375in}
#+LaTeX_HEADER: \addtolength{\evensidemargin}{-.875in}
#+LaTeX_HEADER: \addtolength{\textwidth}{0.75in}

* Question One
  Below is the Zone generated by using the grammar G_z.

  #+BEGIN_CENTER
  Starting values: $u = (14, 37, 2), w = \varnothing, v = \varnothing, l_o = 2$
  #+END_CENTER

  #+BEGIN_LaTeX
    \begin{equation*}
      \begin{split}
        S(u, v, w) \rightarrow^1 & A(u, v, w) \\
                   \rightarrow^{2_1} & t(h_1^o(u), l_o + 1)A((0, 0, 0), g(h_1^o(u), w), zero) \\ \\
                   & h_1^o(14, 37, 2) = (B, t_b) \\
                   & B_t = a(23)a(37) \\
                   & v = g(h_1^o(14, 37, 2), w) = g(Bishop, B_t, w) = \{23, 37\} \\
                   & \text{These two points are 1, all others are 0.} \\ \\
                   \rightarrow^{2_1} & t(B, t_b, 3) (A(0, 0, 0), v, w) \\ \\
                   & TIME(z) = DIST(z, h_1^o(14, 37, 2)) = DIST(z, B, t_b) = \{23, 37\} \\
                   & \text{These two points are 2 and 3, respectively, all others are 128} \\ \\
                   \rightarrow^3 & t(B, t_b, 3) A(f(u, v), v, w) \\ \\
                   & u = f((0, 0, 0), v) = (1, 1, 0) \\ \\
                   \rightarrow^3 & t(B, t_b, 3) A(u, v, w) \\ \\
                   & NEXTTIME(z) = init(u, NEXTTIME(z)) = 2n = 128 \\
                   & \text{For all z from X, NEXTTIME(z) = 128} \\ \\
      \end{split}
    \end{equation*}
  #+END_LaTeX
  
  We now try to apply production four, but find that it fails, sending us back
  to production three. This process repeats a number of times until all the
  conditions are met. The first change occurs until we reach the first point in
  the trajectory for the Bishop, location 23.

  #+BEGIN_LaTeX
    \begin{equation*}
      \begin{split}
        & u = (1, 22, 0) \\ \\
        \rightarrow^3 & t(B, t_b, 3) A(f(u, v), v, w) \\ \\
        & u = f((1, 22, 0), v) = (1, 23, 2) \\ \\
        \rightarrow^3 & t(B, t_b, 3) A(u, v, w) \\
        & \text{Production four fails} \\
        \rightarrow^3 & t(B, t_b, 3) A(f(u, v), v, w) \\ \\
        & u = f((1, 23, 2), v) = (2, 23, 2) \\
      \end{split}
    \end{equation*}
  #+END_LaTeX

  We are once again stuck in a loop where production four will fail, and we
  apply production three. Upon first inspection, it looks like this loop will
  terminate when we reach the black King. However, since the King cannot make
  it to location 23 within the limited number of moves. The next change occurs
  when $x = 64$.

  #+BEGIN_LaTeX
    \begin{equation*}
      \begin{split}
        & u = (64, 23, 2) \\ \\
        \rightarrow^3 & t(B, t_b, 3) A(f(u, v), v, w) \\ \\
        & u = f((64, 23, 2), v) = (1, 24, 0) \\ \\
        \rightarrow^3 & t(B, t_b, 3) A(u, v, w) \\
        & \text{Production four fails} \\
        \rightarrow^3 & t(B, t_b, 3) A(f(u, v), v, w) \\ \\
        & u = f((1, 24, 2), v) = (1, 25, 0) \\
      \end{split}
    \end{equation*}
  #+END_LaTeX

  Once again we are stuck in a loop where /y/ is being incremented. When $y =
  37$, the loop will not terminate, but the function /f/ will begin to
  increment x.

  #+BEGIN_LaTeX
    \begin{equation*}
      \begin{split}
        & u = (1, 36, 0) \\ \\
        \rightarrow^3 & t(B, t_b, 3) A(f(u, v), v, w) \\ \\
        & u = f((1, 36, 0), v) = (1, 37, 3) \\ \\
        \rightarrow^3 & t(B, t_b, 3) A(u, v, w) \\
        & \text{Production four fails} \\
        \rightarrow^3 & t(B, t_b, 3) A(f(u, v), v, w) \\ \\
        & u = f((1, 37, 3), v) = (2, 37, 3) \\
      \end{split}
    \end{equation*}
  #+END_LaTeX
  
  This will repeat until $x = 50$, the location of the black King. This will be
  the first time all of the requirements for production four will be met.

  #+BEGIN_LaTeX
    \begin{equation*}
      \begin{split}
        & u = (49, 37, 3) \\ \\
        \rightarrow^3 & t(B, t_b, 3) A(f(u, v), v, w) \\ \\
        & u = f((49, 37, 3), v) = (50, 37, 3) \\ \\
        \rightarrow^3 & t(B, t_b, 3) A(u, v, w) \\
        \rightarrow^{4_1} & t(B, t_b, 3) t(h_1(u), TIME(y)) A(u, v, g(h_1(u), w)) \\ \\
        & t_k = a(50)a(43)a(36)a(37) \\
        & h_1 = (King, t_K), TIME(y) = 3 \\
        & w = g(h_1((49, 37, 3), w)) = \{43, 36, 37\} \\
        & \text{Each of the points in the set of /w/ equal 1, all others are 0} \\
        & NEXTTIME(z) = \alpha(z, h_1((49, 37, 3), 1) \\
        & \text{Note that NEXTTIME and w are identical.}
        \rightarrow^{4_1} & t(B, t_b, 3) t(K, t_k, 3) A(u, v, w) \\
      \end{split}
    \end{equation*}
  #+END_LaTeX

  Upon inspection, it appears we have the two trajectories that make up the
  zone. We must still apply subsequent productions of the grammar, however,
  there isn't much that changes. We will apply production three until $x = y =
  64$. Production five is valid since $w \neq \varnothing$ 

  #+BEGIN_LaTeX
    \begin{equation*}
      \begin{split}
        \rightarrow^5 & t(B, t_b, 3) t(K, t_k, 3) A((0, 0, 0), w, \varnothing)
      \end{split}
    \end{equation*}
  #+END_LaTeX

  This will iterate through the entire board again, attempting to find second
  negations. The new value of /v/ (the old /w/) will cause the results of the
  function /f/ to never return a length greater than 0. Thus we only have the
  two trajectories in the zone.

  #+BEGIN_LaTeX
    \begin{equation*}
      \begin{split}
        \rightarrow^5 & t(B, t_b, 3) t(K, t_k, 3) A((64, 64, 0), v, \varnothing) \\
        \rightarrow^6 & t(B, t_b, 3) t(K, t_k, 3)
      \end{split}
    \end{equation*}
  #+END_LaTeX
  
