#+TITLE: Assignment Five
#+AUTHOR: Michael Hunsinger
#+OPTIONS: toc:nil \n:nil ':t f:nil num:nil
#+LaTeX_CLASS_OPTIONS: [a4paper]
#+LATEX_CLASS:  article
#+LaTeX_HEADER: \setlength\parindent{0pt}
#+LaTeX_HEADER: \usepackage{titling}
#+LaTeX_HEADER: \usepackage{multicol}
#+LaTeX_HEADER: \addtolength{\topmargin}{-1.375in}
#+LaTeX_HEADER: \addtolength{\textheight}{1.75in}
#+LaTeX_HEADER: \addtolength{\oddsidemargin}{-.375in}
#+LaTeX_HEADER: \addtolength{\evensidemargin}{-.875in}
#+LaTeX_HEADER: \addtolength{\textwidth}{0.75in}

* Question One
  Below is the Zone generated by using the grammar G_z.

  #+BEGIN_CENTER
  Starting values: $u = (14, 37, 2), w = \varnothing, v = \varnothing, l_o =
  2, n = 64$
  #+END_CENTER

  Before generating the zone, a quick note about the notation that will be
  used. The sets /v, w/ and /TIME/ will be sets of ordered pairs. The first
  number represents the point on the board and the second is theh value at that
  point. So the set $v = \{(28, 2)\}$ means the point at 28 has the value
  of 2. \\

  #+BEGIN_LaTeX
      \begin{equation*}
        \begin{split}
          S(u, v, w) & \rightarrow^{1} A(u, v, w) \\
                     & \rightarrow^{2_{1}} t(B, t_{B}, 3) A((0, 0, 0), v, w) \\ \\
                     & TIME = \{(28, 2), (37, 3)\}, v = \{(28, 1), (37, 1)\} \\
                     & w = \varnothing, NEXTIME = \{x | x \in n, x = 128\} \\ \\
                     & \rightarrow^{3} t(B, t_{B}, 3) A(f((0, 0, 0), v), v, w) \\
                     & \rightarrow^{3} t(B, t_{B}, 3) A((1, 1, 0), v, w) \\
        \end{split}
      \end{equation*}
  #+END_LaTeX

  As illustrated in the step above, when applying $f(u, v)$, we apply the
  second of the two options (since $l \leq 0$). Upon further inspection, we
  will use the same function until $TIME(y + 1) \times v_{(y + 1)} > 0$. This
  will repeat until we reach location 27.

  #+BEGIN_LaTeX
    \begin{equation*}
      \begin{split}
        & \rightarrow^{3} t(B, t_{B}, 3) A(f((1, 27, 0), v), v, w) \\
        & \rightarrow^{3} t(B, t_{B}, 3) A((1, 28, 2), v, w) \\
      \end{split}
    \end{equation*}
  #+END_LaTeX

  Our option for $f(u, v)$ has now changed the first option, that is, /x/ will
  increment. We will do so until the predicate for production four is true. \\

  The possibility will be at location two, where the white King is. However, it
  cannot reach location 28 within one move, thus we repeatedly apply production
  three again. The next location we stop at is location 19, where the white
  Pawn is. As in previous assignments, we assume pawns can only move straigh
  ahead, thus it cannot reach this location. The same problem occurs for the
  other two pawns on the board (locations 36 and 37). \\

  We arrive at the black King at location 50. This still cannot reach location
  28 within three moves, so we move on. Finally, when we reach the black Knight
  at location 55, production four does not fail.
  
  #+BEGIN_LaTeX
    \begin{equation*}
      \begin{split}
        & \rightarrow^{3} t(B, t_{B}, 3) A(f((49, 28, 2), v), v, w) \\
        & \rightarrow^{3} t(B, t_{B}, 3) A((50, 28, 2), v, w) \\
        & \rightarrow^{4_{1}} t(B, t_{B}, 3) t(N, t_{N}, 2) A(u, v, w) \\ \\
        & NEXTTIME = \{(45, 1), (28, 1)\}, w = \{(45, 1), (28, 1)\} \\
      \end{split}
    \end{equation*}
  #+END_LaTeX

  Since $l > 0$, we will increment /x/ until $x = 64$. No other negations will
  be found since there are no more pieces. Because $x = 64$, we will switch to
  use the first function of $f(u, v)$. Because $v = 0$ for all points except
  the main trajectory, we will increment /y/ until we arrive at location 33.

  #+BEGIN_LaTeX
    \begin{equation*}
      \begin{split}
        & \rightarrow^{3} t(B, t_{B}, 3) t(N, t_{N}, 2) A(f((1, 32, 0), v), v, w) \\
        & \rightarrow^{3} t(B, t_{B}, 3) t(N, t_{N}, 2) A((1, 33, 3), v, w) \\
      \end{split}
    \end{equation*}
  #+END_LaTeX
  
  Since $l > 0$, we will apply the first function of $f(u, v)$, thus we will
  increment /x/ repeatedly. \\

  Once again, we find the white King cannot reach location 33 within three
  moves. None of the pawns can reach this location either. When we arrive at
  the black King at location 50, it can reach location 33 within three moves.

  #+BEGIN_LaTeX
    \begin{equation*}
      \begin{split}
        & \rightarrow^{3} t(B, t_{B}, 3) t(N, t_{N}, 2) A((50, 32, 3), v, w) \\
        & \rightarrow^{4_{2}} t(B, t_{B}, 3) t(N, t_{N}, 2) t(K, t_{K}, 3) A(u, v, w) \\ \\
        & NEXTTIME = \{(45, 1), (28, 1), (51, 1), (44, 1), (37, 1)\}, \\
        & w = \{(45, 1), (28, 1), (51, 1), (44, 1), (37, 1)\}
      \end{split}
    \end{equation*}
  #+END_LaTeX

  We find the Knight cannot reach location 33 within three moves (requires
  four). We repeatedly increment /x/ until $x = 64$. Since $x = n = 64$, we
  apply the second function of $f(u, v)$. However, this time, the remainder of
  spaces in /v/ are /0/. As a result, we apply the second option until $y =
  0$, and then begin applying the first function of $f(u,v)$. This will repeat
  until $x = 64$. Since $x = y = n = 64$, production three fails and we apply
  production five.

  #+BEGIN_LaTeX
    \begin{equation*}
      \begin{split}
        & \rightarrow^{5} t(B, t_{B}, 3) t(N, t_{N}, 2) t(K, t_{K}, 3) A(u, w, \varnothing) \\ \\
        & TIME = NEXTTIME = \{(45, 1), (28, 1), (51, 1), (44, 1), (37, 1)\}
      \end{split}
    \end{equation*}
  #+END_LaTeX
  
  We now start from production three again. This time, we are in search of
  second negations.

  #+BEGIN_LaTeX
    \begin{equation*}
      \begin{split}
        & \rightarrow^{3} t(B, t_{B}, 3) t(N, t_{N}, 2) t(K, t_{K}, 3) A(f((0,0,0), v), v, w) \\
      \end{split}
    \end{equation*}
  #+END_LaTeX
  
  We learned from finding the first negation that /v_y/ and /TIME(z)/
  controlled the resulting negations, so we can quickly inspect the board to
  find critical areas. Since the first negations only contain the moves by the
  Knight and King, we begin to look at pieces that can either support them or
  intercept them. \\

  We only find the white Pawn at location 32 can intercept the path of the
  black King at location 44. 

  #+BEGIN_LaTeX
    \begin{equation*}
      \begin{split}
        & \rightarrow^{3} t(B, t_{B}, 3) t(N, t_{N}, 2) t(K, t_{K}, 3) A(f((35,44,1), v), v, w) \\
        & \rightarrow^{3} t(B, t_{B}, 3) t(N, t_{N}, 2) t(K, t_{K}, 3) A((36, 44, 1), v, w) \\
        & \rightarrow^{4_{3}} t(B, t_{B}, 3) t(N, t_{N}, 2) t(K, t_{K}, 3) t(P, t_{P}, 2) A(u, v, w) \\
        & NEXTTIME = \{(44, 1)\}, w = \{(44, 1)\}
      \end{split}
    \end{equation*}
  #+END_LaTeX
  
  This is the only piece that can generate a second negation. We repeatedly
  apply production three until $x = y = n = 64$. However, since $w \neq
  \varnothing$, production five does not fail. However, when we run through the
  grammar again, searching for third negations, we do not find any. Thus,
  production six is applied at the end, removing the nonterminal.

  #+BEGIN_LaTeX
    \begin{equation*}
      \begin{split}
        & \rightarrow^{6} t(B, t_{B}, 3) t(N, t_{N}, 2) t(K, t_{K}, 3) t(P, t_{P}, 2) \\ \\
        & t_{B} = a(28) a(37) \\
        & t_{N} = a(55) a(45) a(37) \\
        & t_{K} = a(50) a(51) a(44) a(37) \\
        & t_{P} = a(36) a(44) \\
      \end{split}
    \end{equation*}
  #+END_LaTeX

* Question Two
  To generate all attack zones in a horizon, we must first modify the first
  production to allow for more attack zones. Since we are applying this to the
  Reti Endgame, lets limit this to two attack zones.

  We will add subscripts to /u, v, w/ to denote which attack zone the variable
  belongs to.

  #+BEGIN_LaTeX
    \begin{equation*}
      Q_{1} S(u_1, v_1, w_1, u_2, v_2, w_2) \rightarrow A(u_1, v_1, w_1) A(u_2, v_2, w_2)
    \end{equation*}
  #+END_LaTeX

  We also need to modify the sixth production to allow us to loop back to
  production two if a nonterminal still exists. 

** Reti Endgame
   Per the Reti Endgame, white begins and makes a draw. Below are the starting
   values, where both pawns are progressing to promotion.
   
   #+BEGIN_CENTER
   $u_1 = (64, 8, 7), w_1 = \varnothing, v_1 = \varnothing, l_{o_{1}} = 7, n =
   64$ \\
   $u_2 = (43, 59, 2), w_2 = \varnothing, v_2 = \varnothing, l_{o_{2}} = 2, n =
   64$ \\
   #+END_CENTER
   
   #+BEGIN_LaTeX
     \begin{equation*}
       \begin{split}
         S(u_1, v_1, w_1, u_2, v_2, w_2) & \rightarrow^{1} A(u_1, v_1, w_1) A(u_2, v_2, w_2) \\
         & \rightarrow^{2_{1}} t(K_w, t_{K_w}, 8) A((0, 0, 0), v_1, \varnothing) A(u_2, v_2, w_2) \\ \\
         & TIME = \{(55, 2), (47, 3), (39, 4), (31, 5), (23, 6), (15, 7), (8, 8)\}, \\
         & v_1 = \{(55, 1), (47, 1), (39, 1), (31, 1), (23, 1), (15, 1), (8, 1)\} \\
         & w_1 = \varnothing, NEXTTIME = \{x | x \in n, x = 128\} \\ \\
         & \rightarrow^{3} t(K_w, t_{K_w}, 8) A((1, 1, 0), v_1, w_1) A(u_2, v_2, w_2) \\
         & ... \\
         & \rightarrow^{3} t(K_w, t_{K_w}, 8) A((1, 8, 8), v_1, w_1) A(u_2, v_2, w_2) \\
         & ... \\
         & \rightarrow^{3} t(K_w, t_{K_w}, 8) A((40, 8, 8), v_1, w_1) A(u_2, v_2, w_2) \\
         & \rightarrow^{4_{1}} t(K_w, t_{K_w}, 8) t(P_b, t_{P_b}, 5) A((40, 8, 8), v_1, w_1) A(u_2, v_2, w_2) \\
         & NEXTTIME = \{(40, 4), (32, 4), (16, 4), (8, 4)\}, \\
         & w = \{(40, 1), (32, 1), (16, 1), (8, 1)\} \\
         & ... \\
         & \rightarrow^{3} t(K_w, t_{K_w}, 8) t(P_b, t_{P_b}, 5) A((41, 8, 8), v_1, w_1) A(u_2, v_2, w_2) \\
         & \rightarrow^{4_{2}} t(K_w, t_{K_w}, 8) t(P_b, t_{P_b}, 5) \\
         & t(K_b, t_{K_b}, 8) A((41, 8, 8), v_1, w_1) A(u_2, v_2, w_2) \\
         & NEXTTIME = \{(40, 4), (32, 4), (16, 4), (8, 4), (34, 2), \\
         & (27, 2), (20, 2), (13, 2), (6, 2), (7, 2)\}, \\
         & w = \{(40, 1), (32, 1), (16, 1), (8, 1), (34, 1), \\ 
         & (27, 1), (20, 1), (13, 1), (6, 1), (7, 1)\} \\
         & ... \\
         & \rightarrow^{4_{3}} t(K_w, t_{K_w}, 8) t(P_b, t_{P_b}, 5) t(K_b, t_{K_b}, 8) \\
         & t(K_{b1}, t_{K_{b1}}, 6) A((41, 15, 7), v_1, w_1) A(u_2, v_2, w_2) \\ \\
         & NEXTTIME = \{(40, 4), (32, 4), (16, 4), (8, 4), (34, 2), \\
         & (27, 2), (20, 2), (13, 2), (6, 2), (7, 2), (14, 1)\}, \\
         & w = \{(40, 1), (32, 1), (16, 1), (8, 1), (34, 1), \\
         & (27, 1), (20, 1), (13, 1), (6, 1), (7, 1), (14, 1)\} \\
         & ... \\
       \end{split}
     \end{equation*}
   #+END_LaTeX

   At this point we see the first attack zone has been generated. We have the
   first main trajectory, the white King from location 64 to location 8 and the
   three first negations. Two of the first negtions belong to the black King
   and the other to the black Pawn. The white Pawn is ignored since it cannot
   reach to support the white King. We also can see that there are no second
   negations for this trajectory. \\

   We now attempt to find the negations for the second attack zone. Since we
   are using a different /w/ and /v/, we don't need to worry about clearing out
   the ones generated from the other attack zone. To keep things concise, let
   /Z_1/ represent the set of trajectories found in the first attack zone.

   #+BEGIN_LaTeX
     \begin{equation*}
       \begin{split}
         & \text{current state} \rightarrow Z_1 A((43, 59, 2), v_2, w_2) \\
         & \rightarrow^{2} Z_1 t(P_w, t_{P_{w}}, 3) A((0, 0, 0), v_2, w_2) \\
         & ... \\
         & \rightarrow^{3} Z_1 t(P_w, t_{P_{w}}, 3) A((41, 59, 2), v_2, w_2) \\
         & \rightarrow^{4_{1}} Z_1 t(P_w, t_{P_{w}}, 3) t(K_{b}, t_{K_{b}}, 3) A((41, 59, 2), v_2, w_2) \\
         & NEXTTIME = \{(50, 1), (59, 1)\}, w = \{(50, 1), (59, 1)\} \\
       \end{split}
     \end{equation*}
   #+END_LaTeX

   This is the only negation for the attack zone. We would have to scan most of
   the board again since /w/ has been modified. But Nothing could reach this
   trajectory in time. \\

   Thus, we have created the two attack zones for the Reti Endgame.

   #+BEGIN_LaTeX
     \begin{equation*}
       t(K_w, t_{K_w}, 8) t(P_b, t_{P_b}, 5) t(K_b, t_{K_b}, 8) t(K_{b1}, t_{K_{b1}}, 6) t(P_w, t_{P_{w}}, 3) t(K_{b}, t_{K_{b}}, 3)
     \end{equation*}
   #+END_LaTeX
