#+TITLE: Assignment Two
#+AUTHOR: Michael Hunsinger
#+OPTIONS: toc:nil \n:nil ':t f:nil num:nil
#+LaTeX_CLASS_OPTIONS: [a4paper]
#+LATEX_CLASS:  article
#+LaTeX_HEADER: \setlength\parindent{0pt}
#+LaTeX_HEADER: \usepackage{titling}
#+LaTeX_HEADER: \addtolength{\topmargin}{-1.375in}
#+LaTeX_HEADER: \addtolength{\textheight}{1.75in}
#+LaTeX_HEADER: \addtolength{\oddsidemargin}{-.375in}
#+LaTeX_HEADER: \addtolength{\evensidemargin}{-.875in}
#+LaTeX_HEADER: \addtolength{\textwidth}{0.75in}

* Question One
** Derivation
   You will find the derivation tree below for the modified Missionaries and
   Cannibals problem, with four membors of each party. A small problem arises
   since the boat's capacity is /n - 1/, where /n/ is the members of one party,
   and both partys have /n/ members. \\

   Assume the same starting conditions, where /c/ is the number of cannibals and
   /m/ is the number of missionaries on the target side of the river. All
   cannibals and missionaries are on the starting side of the river, thus /c =
   0/ and /m = 0/.

   \begin{equation}
   \begin{split}
   S(c, m) \rightarrow^1 & A(1,1) \\
   \rightarrow^2 & p(1,1)A(3,0) \\
   \rightarrow^2 & p(1,1)p(3,0)A(2,2) \\
   \rightarrow^2 & p(1,1)p(3,0)p(2,2)A(1,3) \\
   \rightarrow^2 & p(1,1)p(3,0)p(2,2)p(1,3)A(2,3) \\
   \rightarrow^2 & p(1,1)p(3,0)p(2,2)p(1,3)p(2,3)A(3,3) \\
   \rightarrow^2 & p(1,1)p(3,0)p(2,2)p(1,3)p(2,3)p(3,3)A(3,4) \\
   \rightarrow^2 & p(1,1)p(3,0)p(2,2)p(1,3)p(2,3)p(3,3)p(3,4)A(4,4) \\
   \rightarrow^3 & p(1,1)p(3,0)p(2,2)p(1,3)p(2,3)p(3,3)p(3,4)p(4,4) \\
   \end{split}
   \end{equation}

** Grammar
   Below is the general controlled grammar for the Missionaries and Cannibals
   problem. Most of the changes occur in the functions and predicates.

   Let /c/ be the number of cannibals and /m/ be the number of missionaries on
   the target side of the river, and /n/ be the number of members in each
   party. If we assume the capacity of the boat is also /n/, then much of the
   problem stays the same.

   | L | Q   | Kernel                                        | F_T         | F_F         |
   | 1 | Q_1 | S(c,m) \rightarrow A(c + 1, m + 1)            | {2}         | \varnothing |
   | 2 | Q_2 | A(c,m) \rightarrow p(c, m)A(f_1(c,m), f_2(m)) | {2}         | {3}         |
   | 3 | Q_3 | A(c,m) \rightarrow p(c, m)                    | \varnothing | \varnothing |

   - Predicates
     - /Q_1/ = true
     - /Q_2(c, m)/ = true if $(c > 0 \wedge c < n) \vee (m > 0 \wedge m < n)$
     - /Q_3(c, m)/ = false if $(c = n \wedge m = n) \vee ((c > m) \vee (3 - c) >
       (3 - m))$
   - Functions
     - The functions stay the same as well, only replacing /n/ where there are /3/s.

* Question Two
** Grammar
   Below is a derivation for the Tower of Hanoi with four pivots and /n/ disks.

   | L | Q   | Kernel                                                                             | F_T | F_F         |
   | 1 | Q_1 | S(n,x,y) \rightarrow A(n,x,y)                                                      | {2} | \varnothing |
   | 2 | Q_2 | A(n,x,y) \rightarrow A(f_1(n),x,f_2(x,y,z)),p(n,x,y)A(f_1(n),f_2(x,y,z))           | {2} | {3}         |
   | 3 | Q_3 | A(n,x,y) \rightarrow p(n,x,y)                                                      | {2} | \varnothing |

   
** Derivation
   
